---
- hosts: qa
  become: true
  tasks:
    - yum:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=true
    - raw: "echo Hello from the webserver... | sudo tee /var/www/html/index.html"
