FROM python:3.9-slim
RUN ["apt-get", "update"]
RUN ["apt-get", "-y", "install", "sudo"]
RUN ["apt-get", "-y", "install", "vim"]
RUN useradd --create-home --shell /bin/bash mutility_user
RUN adduser mutility_user sudo
USER mutility_user
WORKDIR /home/mutility_user
COPY ./maintenance-utility/ ./
RUN pip3 install --no-cache-dir -r config/requirements.txt
CMD ["bash"]
